(()=>{const mount=()=>{if(document.querySelector('link[data-listing-typography]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/review/shared/listing-typography.css?v=price-stars-3';l.dataset.listingTypography='';document.head.append(l)};if(document.head)mount();else document.addEventListener('DOMContentLoaded',mount,{once:true})})();
(()=>{const mount=()=>{if(document.querySelector('link[data-app-safe-area]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/review/shared/app-safe-area.css?v=font-parity-4';l.dataset.appSafeArea='';document.head.append(l)};if(document.head)mount();else document.addEventListener('DOMContentLoaded',mount,{once:true})})();
(()=>{const mount=()=>{const l=document.createElement('link');l.rel='stylesheet';l.href='/review/shared/no-status-chrome.css';document.head.append(l)};if(document.head)mount();else document.addEventListener('DOMContentLoaded',mount,{once:true})})();
// Register before screen-local handlers, so the master owns cross-screen navigation.
(()=>{let w=window.parent;while(w!==window){try{if(w.ConsumerFlow){w.ConsumerFlow.bind(document);break}if(w===w.parent)break;w=w.parent}catch{break}}})();
// Shared sticky controls build on the same safe-area tokens as every screen.
(()=>{const mount=()=>{if(document.querySelector('script[data-shared-sticky]'))return;const css=document.createElement('link');css.rel='stylesheet';css.href='/review/shared/sticky-headers.css';document.head.append(css);const script=document.createElement('script');script.src='/review/shared/sticky-headers.js';script.dataset.sharedSticky='';document.head.append(script)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount()})();
(()=>{const mount=()=>{const script=document.createElement('script');script.src='/review/shared/cart-detail-polish.js';document.head.append(script)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount()})();
(()=>{const mount=()=>{if(document.querySelector('script[data-shared-search-dock]'))return;const css=document.createElement('link');css.rel='stylesheet';css.href='/review/shared/search-dock.css?v=inactive-store-hub-1';document.head.append(css);const script=document.createElement('script');script.src='/review/shared/search-dock.js?v=inactive-store-hub-1';script.dataset.sharedSearchDock='';document.head.append(script)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount()})();
// Shared nonsearch navigation uses the canonical store's Prism Back24 glyph.
(()=>{const mount=()=>{if(document.querySelector('script[data-navigation-icons]'))return;const css=document.createElement('link');css.rel='stylesheet';css.href='/review/shared/navigation-icons.css?v=hero-white-2';document.head.append(css);const script=document.createElement('script');script.src='/review/shared/navigation-icons.js';script.dataset.navigationIcons='';document.head.append(script)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount()})();
(()=>{const s=document.createElement('script');s.src='/review/shared/touch-interactions.js?v=1';document.head.append(s)})();
