// One stationary status bar for HTML prototypes. Recorded video chrome is untouched.
(()=>{if(document.querySelector('#fixed-phone-status'))return;
const old='.status,.gxc-status-bar,.scroll-header__status-bar,.gxk-status-bar,.gxs-status-bar,.status-bar,.ios-status-bar,.p1-status-bar';
function clean(doc){if(!doc||doc.querySelector('#hide-prototype-status'))return;const style=doc.createElement('style');style.id='hide-prototype-status';style.textContent=old+'{visibility:hidden!important}';doc.head.append(style);doc.querySelectorAll('iframe').forEach(f=>{try{clean(f.contentDocument)}catch{}f.addEventListener('load',()=>{try{clean(f.contentDocument)}catch{}})});}
clean(document);
const chrome=document.createElement('div');chrome.id='fixed-phone-status';chrome.setAttribute('aria-hidden','true');chrome.innerHTML='<b>9:41</b><svg width="68" height="18" viewBox="0 0 68 18"><g fill="currentColor"><rect x="1" y="11" width="3" height="5" rx="1"/><rect x="6" y="8" width="3" height="8" rx="1"/><rect x="11" y="5" width="3" height="11" rx="1"/><rect x="16" y="2" width="3" height="14" rx="1"/></g><path d="M26 6q7-7 14 0m-11 3q4-4 8 0m-5 3 1 1 1-1" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><rect x="46" y="3" width="18" height="11" rx="3" fill="none" stroke="currentColor" opacity=".5"/><rect x="48" y="5" width="14" height="7" rx="1.5" fill="currentColor"/><path d="M66 6v5" stroke="currentColor" stroke-width="2"/></svg>';
Object.assign(chrome.style,{position:'fixed',top:'0',left:'50%',transform:'translateX(-50%)',width:'393px',maxWidth:'100%',height:'59px',padding:'19px 28px 0',display:'flex',justifyContent:'space-between',boxSizing:'border-box',font:'600 15px -apple-system,BlinkMacSystemFont,Arial,sans-serif',pointerEvents:'none',zIndex:'10000',color:'#191919'});const device=document.querySelector('#device');if(device){chrome.style.position='absolute';device.append(chrome)}else document.body.append(chrome);
window.setPhoneChromeTone=t=>chrome.style.color=t==='light'?'white':'#191919';
})();
