const A='assets/',app=document.querySelector('#app');
const state={screen:'tracking',answers:[null,null,null],photo:null,note:'',stars:0};
const questions=['Was it filling for one?*','Did it have protein, vegetables, and carbs?*','Was the Merchant’s photo and description accurate?'];
const img=(name,cls='',alt='')=>`<img class="${cls}" src="${name.startsWith("/")?name:A+name}" alt="${alt}">`;
const button=(label,action,cls='primary')=>`<button class="${cls}" data-action="${action}">${label}</button>`;
const prismPaths={"add": "M11 21v-8H3a1 1 0 1 1 0-2h8V3a1 1 0 1 1 2 0v8h8a1 1 0 1 1 0 2h-8v8a1 1 0 1 1-2 0", "right": "M12.793 3.793a1 1 0 0 1 1.414 0L21 10.586a2 2 0 0 1 0 2.828l-6.793 6.793a1 1 0 1 1-1.414-1.414L18.586 13H3a1 1 0 1 1 0-2h15.586l-5.793-5.793a1 1 0 0 1 0-1.414", "close": "M18.793 3.793a1 1 0 1 1 1.414 1.414L13.414 12l6.793 6.793a1 1 0 0 1-1.414 1.414L12 13.414l-6.793 6.793a1 1 0 0 1-1.414-1.414L10.586 12 3.793 5.207a1 1 0 1 1 1.414-1.414L12 10.586z"};
const prismIcon=name=>`<svg class="review-prism-icon" width="24" height="24" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path fill="currentColor" d="${prismPaths[name]}"></path></svg>`;
const sheetTop=(back='tracking')=>`<div class="sheet-top">${button(prismIcon('close'),back,'close')}<button class="help" data-action="help">Get help</button></div>`;
const trackingMarkup=()=>`<section class="tracking"><div class="map-wrap">${img('map.png','map','Order map')}${img('pin-home.svg','pin pin-home')}${img('pin-store.svg','pin pin-store')}<div class="pin pin-car">${img('pin-car.svg')}${img('car-glyph.svg','car-glyph')}</div></div><div class="top">${button('×','home','')}${button('Help','help','')}</div><div class="order-info">${img('merchant.png','merchant-avatar')}<h1>Picking up order</h1><p>Arrives between <b>12:30 – 12:45 PM</b></p><div class="progress"><span>${img('step-dd.svg')}</span><span>${img('step-store.svg')}</span><span>${img('step-car.svg')}</span><span>${img('step-home.svg')}</span></div><p class="order-description">Comal Next Door is preparing your order. Your Dasher is heading to the store.</p><div class="dasher">${img('dasher.png','','Your Dasher')}<div>Your Dasher<small>Emma</small></div><div class="dasher-actions"><button data-action="tip">Add tip</button><button data-action="help" aria-label="Call Dasher"><svg viewBox="0 0 24 24"><path d="M6 3 3 6c0 8 7 15 15 15l3-3-5-4-2 2c-3-1-5-3-6-6l2-2Z"/></svg></button><button data-action="help" aria-label="Message Dasher"><svg viewBox="0 0 24 24"><path d="M4 4h16v13h-5l-4 4v-4H4Z"/><path d="M8 9h8" stroke="white" stroke-width="2"/></svg></button></div></div>${button('<span class="chevron"></span> Order details','details','details')}<button class="entry" data-action="form"><span class="credit-icon">${img('credit-badge.svg')}<b>5</b></span><span><strong>Give feedback, earn $5</strong><small>Take a photo of this meal box<br>before you eat to get a $5 credit</small></span><span class="arrow">${prismIcon('right')}</span></button></div></section>`;
const background=()=>`<div class="review-tracking-backdrop" inert aria-hidden="true">${trackingMarkup()}</div><div class="shade"></div>`;
function tone(light){window.setPhoneChromeTone?.(light?'light':'dark');document.documentElement.dataset.phoneTone=light?'light':'dark'}
function sheet(content,actions,cls=''){return background()+`<section class="sheet ${cls}">${sheetTop(cls==='guidance'?'form':'tracking')}<div class="body">${content}</div><footer class="actions">${actions}</footer></section>`}
function render(screen=state.screen){const previous=state.screen;state.screen=screen;tone(['camera','preview'].includes(screen));
 if(screen==='tracking')app.innerHTML=trackingMarkup();
 if(screen==='form'){app.innerHTML=sheet(`<h1>Give Meal Box feedback</h1><p class="intro"><b>Earn a $5 credit</b> for taking a qualifying photo of your Comal Next Door Meal Box before eating. Your response is private and helps us improve future Meal Boxes. <button class="link" data-action="terms">Terms apply</button></p><div class="meal-card"><div class="meal">${img('burrito.png','','Carnitas Burrito')}<div><strong>Carnitas Burrito</strong><small>$12.00</small></div></div>${questions.map((q,i)=>`<div class="question"><span>${q}</span><div class="choices">${['down','up'].map((v)=>`<button class="vote" data-vote="${i}:${v}" aria-label="${q} ${v==='up'?'Yes':'No'}" aria-pressed="${state.answers[i]===v}">${img('thumb-'+v+'.svg')}</button>`).join('')}</div></div>`).join('')}<div class="photos">${state.photo?`<button data-action="preview">${img(state.photo,'thumb','Your captured meal photo')}</button>`:''}<button class="add-photo" data-action="guidance" aria-label="Add photos"><span>${prismIcon('add')}</span></button>${state.photo?'':'Add photos*'}</div></div><textarea aria-label="Additional feedback" placeholder="Did you have any other feedback?"></textarea>`,button('Submit','submit'));app.querySelector('textarea').value=state.note;validate();}
 if(screen==='guidance')app.innerHTML=sheet(`<div class="examples"><div class="example">${img('photo-bad.png','','Example: incomplete framing')}<span class="badge">${img('cross.svg')}</span></div><div class="example good">${img('photo-good.png','','Example: full meal with utensil')}<span class="badge">${img('check.svg')}</span></div></div><h1>Photo guidance</h1><p class="guide-description">Take the photo before eating. Credits are only issued for high-quality images, which help us improve future Meal Boxes.</p>${[['utensil.svg','Add utensil for scale'],['bowl.svg','Take off the lid and show the full dish in its container'],['light.svg','Clear the background and turn up the lights.']].map(([icon,text])=>`<div class="guide-row">${img(icon)}<span>${text}</span></div>`).join('')}`,button('Take a photo','camera')+button('Add Photo from Library','library','secondary'),'guidance');
 if(screen==='camera')app.innerHTML=`<section class="camera"><div class="camera-top"><button data-action="guidance" aria-label="Close camera">${prismIcon('close')}</button><button data-action="flash" aria-label="Toggle flash" aria-pressed="false">${img('flash.svg')}</button></div><div class="viewfinder">${img('/assets/deck-final/affordable-meals/customer-reviews/review-1.jpg','food-motion','Simulated camera view of a meal')}${img('focus.svg','focus')}<div class="camera-start"></div></div><div class="camera-hint"><b>Position your dish within the border</b><p>Include utensil in photo for scale</p></div><button class="shutter" data-action="capture" aria-label="Take photo">${img('shutter.svg')}</button></section>`;
 if(screen==='preview')app.innerHTML=`<section class="camera"><div class="camera-top"><button class="close" data-action="form" aria-label="Close photo">${prismIcon('close')}</button></div>${img(state.photo||'/assets/deck-final/affordable-meals/customer-reviews/review-1.jpg','preview-photo','Captured meal photo')}<footer class="actions">${button('Use photo','use')}${button('Retake','camera','secondary')}</footer></section>`;
 if(screen==='thanks')app.innerHTML=background()+`<section class="sheet thanks"><div class="body">${img('credit.svg','credit-art')}<h2>Thanks for your Meal Box feedback!</h2><p>You’ll receive a $5 credit. You’re helping improve Meal Box quality for your community.</p></div><footer class="actions">${button('Done','dismiss-review')}${button('Leave a public review','public','secondary')}</footer></section>`;
 if(screen==='library')app.innerHTML=sheet('<h1>Choose a food photo</h1><p class="intro">Demo photo library</p><div class="library">'+["/assets/deck-final/affordable-meals/customer-reviews/review-1.jpg", "/assets/deck-final/affordable-meals/customer-reviews/review-2.avif", "/assets/deck-final/affordable-meals/customer-reviews/review-3.jpg", "/assets/deck-final/affordable-meals/customer-reviews/review-4.jpg", "/assets/deck-final/affordable-meals/customer-reviews/review-5.jpg", "/assets/deck-final/affordable-meals/customer-reviews/review-6.jpg"].map(name=>`<button data-photo="${name}">${img(name,'','Select food photo')}</button>`).join('')+'</div>',button('Cancel','guidance','secondary'));
 if(screen==='public')app.innerHTML=sheet('<h1>How was Comal Next Door?</h1><p class="intro">Share your experience with other customers</p><div class="rating-stars">'+[1,2,3,4,5].map(n=>`<button data-star="${n}" aria-label="${n} stars" class="${n<=state.stars?'active':''}">★</button>`).join('')+'</div><textarea placeholder="Leave a public review" aria-label="Public review"></textarea>',button('Submit review','public-submit'));
 if(screen==='home')app.innerHTML=background().replace('<div class="shade"></div>','');
 if(screen!==previous&&!(screen==='form'&&previous==='preview')&&!matchMedia('(prefers-reduced-motion:reduce)').matches){const el=app.querySelector('.sheet,.camera');el?.animate([{transform:screen==='camera'?'translateY(100%)':'translateY(45px)'},{transform:'translateY(0)'}],{duration:screen==='camera'?420:320,easing:'cubic-bezier(.22,.75,.2,1)'});}
 const vf=app.querySelector('.viewfinder');if(vf)vf.onpointermove=e=>{const r=vf.getBoundingClientRect(),photo=vf.querySelector('.food-motion');photo.style.animation='none';photo.style.transform=`rotate(0deg) scale(1.08) translate(${(e.clientX-r.left-r.width/2)*.06}px,${(e.clientY-r.top-r.height/2)*.06}px)`};
}
function validate(){const b=app.querySelector('[data-action=submit]');if(b)b.disabled=!(state.answers[0]&&state.answers[1]&&state.photo)}
function toast(text){app.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=text;app.append(el);setTimeout(()=>el.remove(),3200)}
app.addEventListener('input',e=>{if(e.target.matches('[aria-label="Additional feedback"]'))state.note=e.target.value});
app.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.vote){const [i,v]=b.dataset.vote.split(':');state.answers[i]=v;b.parentElement.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));validate();return}if(b.dataset.photo){state.photo=b.dataset.photo;render('preview');return}if(b.dataset.star){state.stars=Number(b.dataset.star);app.querySelectorAll('[data-star]').forEach(x=>x.classList.toggle('active',Number(x.dataset.star)<=state.stars));return}
 const a=b.dataset.action;if(!a)return;if(a==='capture'){b.disabled=true;const f=document.createElement('div');f.className='flash-layer';app.append(f);await new Promise(r=>setTimeout(r,180));state.photo='/assets/deck-final/affordable-meals/customer-reviews/review-1.jpg';render('preview');return}if(a==='dismiss-review'){render('tracking');return}if(a==='use'){state.photo=state.photo||'/assets/deck-final/affordable-meals/customer-reviews/review-1.jpg';render('form');return}if(a==='submit'){render('thanks');return}if(a==='reset'){state.answers=[null,null,null];state.photo=null;state.note='';render('tracking');return}if(a==='flash'){b.setAttribute('aria-pressed',String(b.getAttribute('aria-pressed')!=='true'));return}if(a==='tip'){toast('Tip options are not included in this review demo.');return}if(a==='terms'){toast('Credit is issued for a qualifying, high-quality photo taken before eating.');return}if(a==='help'){toast('For an issue with your order, use DoorDash Help. This demo does not contact support.');return}if(a==='details'){toast('Comal Next Door · Carnitas Burrito · $12.00');return}if(a==='public-submit'){if(!state.stars){toast('Choose a rating first');return}render('home');toast('Thanks for sharing your review');return}render(a);
});
render();

// Flow-map entry points render the same live screens, not screenshot copies.
const flowScreen=new URLSearchParams(location.search).get('flowScreen');
if(['tracking','form','guidance','camera','preview','thanks'].includes(flowScreen)){
 if(['preview','thanks'].includes(flowScreen))state.photo='/assets/deck-final/affordable-meals/customer-reviews/review-1.jpg';
 render(flowScreen);
}
