/* Slides 2–3: source-backed context; all figures are program context, not personal impact. */
Object.assign(SLIDES[1],{
 title:'Affordability limits how often people use DoorDash',
 body:'A reason to leave. An opportunity to return.',
 note:'55% describes a concern reported by churned customers, not the percentage of churn caused by affordability. Approximately 40% cited meals under $15 as a top reason to return. The product brief does not provide the underlying survey sample size or field dates.',
 sources:[{title:'Affordable Meals MVP · customer evidence',url:'https://docs.google.com/document/d/1R1p6rQKABOSAm8zRFQ7GEomRbRaoss6N5JiE3qTJMu4/edit',ownership:'Program brief; underlying survey methodology not located'},{title:'2026 planning · Meal Box growth target',url:'https://docs.google.com/document/d/1a0RJEmznnCd-6weq6fTaZNYpzhYdbwoNdzjWtcftb6w/edit',ownership:'Planning target, not realized revenue'}]
});
Object.assign(SLIDES[2],{
 title:'Make affordability an everyday habit',
 body:'Two goals for Affordable Meals',
 note:'These are two portfolio-level goals across Affordable Meals, not two measured Meal Box outcomes. Goal 1: viable economics beyond recurring subsidies. Historical example: Q1 2023 Tax-Refund Go-Big campaign spent $2.03M on promotions and forecast ~20-month payback; this does not prove all promotions are unsustainable. The older $5.8M GMV and -$1.6M variable profit had different measurement windows and are intentionally omitted. Goal 2: affordable everyday eating across more occasions. H2 planning reports 44% of 1P Basics volume from early morning or late night; this is existing volume mix, not incremental occasions. Breakfast and late-night needs are supported by the strategy; dessert/new late-night concepts are planned tests. Do not attribute these program findings personally.',
 sources:[{title:'Tax-Refund Go-Big · historical campaign readout',url:'https://docs.google.com/document/d/13WZmEWKlGxrDRyzb9eVfUBTvp6DhUzZvdXVVqLO2A2E/edit',ownership:'One 2023 promotion; not Meal Box economics or a universal promotion conclusion'},{title:'Affordable Meals H2 2026 planning · Basics deep dive',url:'https://docs.google.com/document/d/1iwfvTY8hoUp9G9tJKEe4mxZEPiu754h-KNN1McfUxSY/edit',ownership:'1P Basics volume mix; broader program strategy'}]
});
function renderAmbitionStats(s){
 const index=SLIDES.indexOf(s);if(index!==1&&index!==2)return;
 const slide=document.querySelector('#slide');slide.classList.add('evidence-slide');if(index===1)slide.classList.add('customer-evidence');else slide.classList.add('two-goals-slide');
 const stage=slide.querySelector('.stage');stage.setAttribute('aria-label','Business context statistics');
 stage.innerHTML=index===1?`<div class="stat-sheet"><div class="number-pair"><article><strong>55<span>%</span></strong><p>of churned customers wanted<br>more affordable options</p></article><article><strong>~40<span>%</span></strong><p>cited meals under $15<br>as a top reason to return</p></article></div></div>`:`<div class="affordability-goals"><article><small>01 · A SUSTAINABLE MODEL</small><h3>Affordable by design.<br>Beyond the next promo.</h3><p>Build meal programs that work for customers, merchants and DoorDash over time.</p><div class="goal-proof"><strong>~20 months</strong><span>projected payback in one historical win-back campaign</span></div><footer>2023 campaign · $2.03M promotional spend.<br>A reason to explore another model—not proof that every promo fails.</footer></article><article><small>02 · MORE EATING OCCASIONS</small><h3>An everyday option.<br>Across more of the day.</h3><p>Lower prices and new formats make room for breakfast, everyday meals, snacks and late-night needs.</p><div class="goal-proof"><strong>44%</strong><span>of 1P Basics volume came from early morning or late night</span></div><footer>H1 2026 · 1P Basics, not Meal Box.<br>Volume mix—not a claim of incremental occasions.</footer></article></div>`;
 if(!matchMedia('(prefers-reduced-motion: reduce)').matches){[slide.querySelector('.copy'),...stage.querySelectorAll('article')].forEach((el,i)=>el.animate([{opacity:0,transform:'translateY(26px)'},{opacity:1,transform:'translateY(0)'}],{duration:950,delay:i*180,fill:'backwards',easing:'cubic-bezier(.22,1,.36,1)'}));}slide.querySelector('.slide-foot.right').textContent=`${index+1} · Business context`;
}
