// Shared visual vocabulary for the consumer story; editable narrative stays in slides.js.
function consumerGlyph(name){const paths={home:'M3 11 12 3l9 8M5 10v11h14V10M9 21v-8h6v8',search:'M16 16l5 5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',store:'M3 9h18l-2-6H5L3 9Zm2 0v12h14V9M9 21v-7h6v7',discover:'M12 2v4m0 12v4M2 12h4m12 0h4M5 5l3 3m8 8 3 3M5 19l3-3m8-8 3-3',learn:'M4 4h7a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H4V4Zm16 0h-3M17 9h3m-3 5h3',check:'m5 12 5 5L20 6',return:'M4 10a8 8 0 1 1 1 8M4 4v6h6'};return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+paths[name]+'"/></svg>'}
function renderConsumerOpening(s){
 const slide=document.querySelector('#slide');
 if(s.layout==='merchant-collaboration'){slide.innerHTML=`<figure class=collaboration-photo><img src="${DECK_ASSETS.merchantCollaboration}" alt="Restaurant team collaborating at a table"></figure><section class=collaboration-copy><p class=collaboration-eyebrow>${esc(s.eyebrow||'')}</p><h2>${esc(s.title)}</h2><p class=collaboration-benefit>${esc(s.body)}</p><div class=mealbox-divider-meals>${DECK_ASSETS.mealboxDividerMeals.map((src,i)=>`<figure class=meal-${i}><img src="${src}" alt="Representative meal"></figure>`).join('')}</div></section>`;return;}
 if(s.layout==='mealbox-divider'){slide.innerHTML='<div class=mealbox-divider-copy><p>Deep dive</p><h2>Restaurant<br>$12 Meal Boxes</h2></div><div class="mealbox-divider-meals supplied-bowls">'+DECK_ASSETS.mealboxDividerBowls.map((b,i)=>`<figure class="meal-${i}"><svg viewBox="${b.viewBox}" role="img" aria-label="${b.label}"><image href="${b.src}" width="${b.width}" height="${b.height}"/></svg></figure>`).join('')+'</div>';return;}
 if(s.layout==='consumer-divider'){slide.innerHTML='<h2>The consumer experience</h2>';return;}
 if(s.layout==='consumer-context')slide.innerHTML=`<section class="consumer-question"><h2>${esc(s.title)}</h2></section><div class="consumer-experience-stages">${s.stages.map(label=>`<p>${esc(label)}</p>`).join('')}</div>`;
 if(s.layout==='consumer-entry-points')slide.innerHTML='<section class="discovery-title"><h2>Discovery</h2></section><div class="discovery-stack">'+s.entries.map((e,i)=>'<article><div class="discovery-icon">'+consumerGlyph(['home','search','store'][i])+'</div><div><p>'+esc(e.quote)+'</p><h3>'+esc(e.title)+'</h3></div></article>').join('')+'</div>';
 if(s.layout==='consumer-journey')slide.innerHTML='<section class="journey-heading"><h2>Meet consumers<br>where they already are</h2></section><div class="visual-journey">'+[{icon:'discover',title:'Discover',sub:'In their routine'},{icon:'learn',title:'Understand',sub:'The meal and the value'},{icon:'check',title:'Try',sub:'Reinforce the benefit'},{icon:'return',title:'Return & share',sub:'Keep the loop going'}].map((v,i)=>'<article><div class="journey-symbol">'+consumerGlyph(v.icon)+'</div><h3>'+v.title+'</h3><p>'+v.sub+'</p></article>').join('')+'</div><p class="outside-touchpoints"><b>Before the app</b> Emails · paid social · push · merchant flyers</p>';
 if(['consumer-context','consumer-journey','consumer-entry-points'].includes(s.layout)&&!matchMedia('(prefers-reduced-motion: reduce)').matches)slide.querySelectorAll('h2,.question-support,article,.outside-touchpoints,.intent-axis').forEach((el,i)=>el.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:500,delay:Math.min(i*90,450),easing:'cubic-bezier(.2,.7,.2,1)',fill:'both'}));
}
