/* Two compositions share the same dish asset and slide; switch without duplicating deck content. */
const originalMealReveal=renderMealReveal;
renderMealReveal=function(){const variant=new URLSearchParams(location.search).get('meal')||'annotated';if(variant==='glass'){originalMealReveal();addMealOptions(variant);return;}if(variant==='annotated'){renderMealAnatomy();addMealOptions(variant);return;}const slide=document.querySelector('#slide');slide.className='meal-option meal-option-'+variant;
const copy='<div class="meal-option-copy"><small>RESTAURANT MEAL BOX</small><h2>$12 meals.<br>A full plate.</h2><p>Top-rated restaurants.<br>Filling & balanced.<br>Quality checked.</p></div>';
slide.innerHTML=variant==='annotated'?`<div class="annotated-copy">${copy}<div class="ingredient-labels"><span>Protein</span><span>Veggies</span><span>Carbs</span></div></div><div class="annotated-dish">${mealDish()}</div><svg class="ingredient-lines" viewBox="0 0 1000 700" preserveAspectRatio="none" aria-hidden="true"><path d="M300 420 H440 L665 410"/><path d="M300 475 H440 L630 465"/><path d="M300 530 H435 L675 305"/><circle cx="665" cy="430" r="3"/><circle cx="630" cy="465" r="3"/><circle cx="675" cy="305" r="3"/></svg><small class="ingredient-note">Illustrative callouts · adjust to final meal photo</small>`:`<div class="cropped-dish">${mealDish()}</div>${copy}`;
if(variant==='annotated'){const box=slide.getBoundingClientRect(),labels=slide.querySelectorAll('.ingredient-labels span'),svg=slide.querySelector('svg');svg.setAttribute('viewBox','0 0 '+box.width+' '+box.height);const targets=[[.70,.53],[.68,.58],[.68,.37]];svg.innerHTML=Array.from(labels).map((label,i)=>{const r=label.getBoundingClientRect(),x=r.left-box.left+90,y=r.top-box.top+r.height/2,tx=targets[i][0]*box.width,ty=targets[i][1]*box.height;return '<path d="M'+x+' '+y+' H'+(box.width*.43)+' L'+tx+' '+ty+'"/><circle cx="'+tx+'" cy="'+ty+'" r="3"/>';}).join('');}if(!matchMedia('(prefers-reduced-motion: reduce)').matches){slide.querySelector('.meal-dish').animate(variant==='crop'?[{transform:'translateX(90px) scale(.82)'},{transform:'translateX(0) scale(1)'}]:[{transform:'scale(.88)',opacity:0},{transform:'scale(1)',opacity:1}],{duration:1400,easing:'cubic-bezier(.22,1,.36,1)'});slide.querySelector('.meal-option-copy').animate([{opacity:0,translate:'0 15px'},{opacity:1,translate:'0 0'}],{duration:750,delay:450,fill:'backwards'});slide.querySelector('.ingredient-lines')?.animate([{opacity:0},{opacity:1}],{duration:800,delay:700,fill:'backwards'});}window.mealRevealOrigin=null;window.mealCardOrigin=null;addMealOptions(variant);};
function addMealOptions(selected){return;const nav=document.createElement('nav');nav.className='meal-options';nav.setAttribute('aria-label','Compare meal compositions');[['annotated','A · Ingredient callouts'],['crop','B · Half dish'],['glass','Original glass']].forEach(([id,label])=>{const b=document.createElement('button');b.textContent=label;b.classList.toggle('selected',id===selected);b.onclick=()=>{const u=new URL(location.href);u.searchParams.set('meal',id);history.replaceState(null,'',u);renderMealReveal();};nav.append(b)});document.querySelector('#slide').append(nav);}

function renderMealAnatomy(){
const origin=window.mealRevealOrigin;originalMealReveal();const slide=document.querySelector('#slide');slide.classList.add('meal-anatomy');slide.querySelector('.headline').textContent='$12 Meal Boxes';slide.querySelector('.meal-subtitle').textContent='Full meals, made with restaurants';const explanation=document.createElement('p');explanation.className='meal-program-summary';explanation.textContent='Familiar dishes. New combinations. One full meal.';slide.querySelector('.meal-reveal-copy').append(explanation);const food=slide.querySelector('.meal-dish');food.getAnimations().forEach(a=>a.cancel());if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const r=food.getBoundingClientRect();food.style.transformOrigin='top left';const start=origin?`translate(${origin.left-r.left}px,${origin.top-r.top}px) scale(${origin.width/r.width})`:'scale(.78)';food.animate([{transform:start,opacity:1},{transform:'translate(0,0) scale(1)',opacity:1}],{duration:1400,easing:'cubic-bezier(.22,1,.36,1)'});}slide.querySelector('.meal-glass').getAnimations().forEach(a=>a.cancel());if(!matchMedia('(prefers-reduced-motion: reduce)').matches)slide.querySelector('.meal-glass').animate([{opacity:0,translate:'0 12px'},{opacity:1,translate:'0 0'}],{duration:650,delay:1650,fill:'backwards'});const labels=slide.querySelector('.meal-principles');labels.getAnimations({subtree:true}).forEach(a=>a.cancel());labels.innerHTML='<p>Carbs</p><p>Protein</p><p>Veggies</p>';
const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('anatomy-leaders');svg.setAttribute('viewBox','0 0 1000 700');svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-hidden','true');svg.innerHTML='<path d="M525 270 L565 245 H615"/><path d="M535 365 L565 355 H615"/><path d="M530 420 L565 455 H615"/><circle cx="525" cy="270" r="2.5"/><circle cx="535" cy="365" r="2.5"/><circle cx="530" cy="420" r="2.5"/>';slide.append(svg);
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){svg.querySelectorAll('path').forEach((path,i)=>{const length=path.getTotalLength();path.animate([{strokeDasharray:length,strokeDashoffset:length,opacity:0},{strokeDasharray:length,strokeDashoffset:0,opacity:1}],{duration:1000,delay:2550+i*120,fill:'backwards',easing:'cubic-bezier(.22,1,.36,1)'});});svg.querySelectorAll('circle').forEach((el,i)=>el.animate([{opacity:0},{opacity:1}],{duration:500,delay:2800+i*120,fill:'backwards'}));labels.querySelectorAll('p').forEach((el,i)=>el.animate([{opacity:0,translate:'-8px 0'},{opacity:1,translate:'0 0'}],{duration:700,delay:2800+i*120,fill:'backwards'}));}}
