function renderMerchantStory(s){window.opsCleanup?.();if(!s.merchant)return;const root=document.querySelector('#slide');if(s.merchant==='divider'){root.className='consumer-divider';root.innerHTML='<h2>Supporting merchants.<br>Scaling the program.</h2>';return;}root.classList.add('merchant-story');const stage=root.querySelector('.stage');const metric=(n,l)=>`<div class="m-metric"><strong>${n}</strong><span>${l}</span></div>`;const ph=(name,detail,cls='')=>`<div class="m-placeholder ${cls}"><span>${name}</span><small>${detail}</small></div>`;
const steps=(rows)=>'<div class="ops-steps">'+rows.map(([a,b,c])=>'<article><h3>'+a+'</h3><p>'+b+'</p><small>'+c+'</small></article>').join('')+'</div>';
if(s.merchant==='scale'){renderOpsScale(root);return;}if(['enroll','quality','report'].includes(s.merchant)){renderOpsDetail(root,s.merchant);return;}if(s.merchant==='process'){renderOpsTimeline(root);return;}
if(s.merchant==='enroll'){stage.innerHTML='<div class="m-status">SELF-ENROLLMENT · WORK IN PROGRESS</div>'+steps([
['Create & approve','Rep and restaurant create3+ meals; rep submits the menu for approval.','Offsite example: finalize today → approve Day2.'],
['Prepare & activate','Coordinate new-dish photography; help upload items and guide POS setup.','Photos Days3–6 → menu setup Day7 → merchandising within24h.'],
['Proposed self-service','Merchant enters meal details, submits dishes and follows setup/status in one place.','People retain exceptions, approval and relationship support.']])+ph('Self-enrollment screenshot','Your Figma22:6257 · replace here','ops-screen')+'<p class="ops-takeaway"><b>Latest activation SLA:12days POS /6days tablet.</b> Elapsed time—not rep labor. Savings not yet measured.</p>';}
if(s.merchant==='quality'){stage.innerHTML='<div class="m-metrics">'+metric('22k','SKUs created · scale context')+metric('68%','live SKUs with any review signal')+metric('25%','live SKUs definitively assessed')+'</div>'+steps([
['Today · gather evidence','Customers submit reviews; launchers and a separate taste-testing channel order and assess meals.','Taste tests resolve uncertainty and cover strategic dishes.'],
['Bottleneck · turn evidence into action','Read text, inspect photos, assess portion/balance/accuracy, record pass/fail, and chase fixes.','Having a review does not mean a dish has been definitively assessed.'],
['Automation · route the right work','Gather customer photos → AI-assisted assessment/summary → humans review failures and uncertainty → merchant feedback.','AI first-pass classification is the offsite desired workflow; do not imply it is fully automated today.']])+'<div class="ops-assets">'+ph('Consumer review','Phone flow')+ph('Submitted photos','Evidence collage')+ph('AI findings → merchant','Summary / ratings & reviews')+'</div><small class="m-caption">September offsite snapshot · denominators differ:22k created vs live-SKU coverage</small>';}
if(s.merchant==='report'){stage.innerHTML=steps([
['Today · build the story by hand','Review store performance, Meal Box sales/orders and new customers; combine SKU ratings, reviews and taste tests.','Reps turn those findings into a performance deck and recommendations.'],
['Then · get a merchant to act','Share results, discuss changes, answer questions and follow up until updates go live.','Quality follow-up baseline:~20%respond; changes take~2weeks.'],
['Proposed · send a useful starting point','Generate a recurring performance email with recommendations, then let merchants inspect detail in the portal.','Keep a real rep contact for advice and exceptions.']])+'<div class="m-report-view">'+ph('Automated performance email','Results · suggestions · contact a rep','ops-screen')+'</div><button class="m-reveal">Show ratings & reviews →</button><small class="m-caption">Planned:Q42026 email MVP /Q12027 full reporting portal · no measured hours saved yet</small>';let open=false;stage.querySelector('.m-reveal').onclick=()=>{open=!open;stage.querySelector('.m-report-view').innerHTML=ph(open?'Merchant ratings & reviews':'Automated performance email',open?'SKU evidence and customer feedback':'Results · suggestions · contact a rep','ops-screen');stage.querySelector('.m-reveal').textContent=open?'← Back to email':'Show ratings & reviews →';};}
}

/* One source of truth for the process story. Days are elapsed milestones, not labor. */
const OPS_TIMELINE=[
 {title:'Find the right restaurants',who:'Sales rep + merchant',detail:'Research, pitch the opportunity and agree on economics.',day:0,time:'Before enrollment · duration unmeasured'},
 {title:'Create and approve the meals',who:'Merchant + rep + approver',detail:'Co-create 3+ dishes and submit the menu for approval.',day:2,time:'Day 2 · menu approval'},
 {title:'Photograph the new dishes',who:'Merchant + photo operations',detail:'Coordinate the shoot and get usable menu imagery.',day:6,time:'Days 3–6 · photography'},
 {title:'Set up and activate',who:'Merchant + rep + menu / POS teams',detail:'Configure items, then turn on merchandising within 24 hours.',day:8,time:'Day 7 + up to 24h · go live'},
 {title:'Maintain quality and grow',who:'Post-sales + merchant',detail:'Review performance, assess quality, recommend changes and follow up.',day:8,time:'Ongoing · labor time unmeasured'}
];
function renderOpsTimeline(root){
 root.className='merchant-story ops-timeline-slide';
 root.innerHTML='<div class="ops-context"><small>THE PROCESS TODAY</small><h2>Find. Build. Maintain.<br>How does this scale?</h2><p>From the first pitch to a live menu—and a relationship that continues after launch.</p><div class="ops-clock"><strong><span id="ops-day">0</span><small> elapsed days</small></strong><span id="ops-clock-label">Before enrollment</span></div><small class="ops-evidence">Time since menu creation · offsite example. Outreach happens before this clock. Not rep labor hours.<br>Latest activation SLA: 12 days POS / 6 days tablet.</small></div><div class="ops-timeline"><div class="ops-spine"></div>'+OPS_TIMELINE.map((x,i)=>'<button class="ops-stop" data-step="'+i+'"><span class="ops-dot">'+(i+1)+'</span><div><small>'+x.who+'</small><h3>'+x.title+'</h3><p>'+x.detail+'</p><b>'+x.time+'</b></div></button>').join('')+'<button class="ops-replay">Replay timeline ↺</button></div>';
 let timers=[],frame=0,current=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 let activeStep=0;function activate(i){activeStep=i;root.querySelectorAll('.ops-stop').forEach((el,j)=>{el.classList.toggle('active',j===i);el.classList.toggle('passed',j<i);el.setAttribute('aria-pressed',String(j===i))});const target=OPS_TIMELINE[i].day,start=current,at=performance.now();cancelAnimationFrame(frame);function tick(now){if(!root.querySelector('#ops-day'))return;const t=reduced?1:Math.min(1,(now-at)/650);current=start+(target-start)*(1-Math.pow(1-t,3));root.querySelector('#ops-day').textContent=Math.round(current);if(t<1)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);root.querySelector('#ops-clock-label').textContent=i===4?'Then ongoing relationship support':OPS_TIMELINE[i].time;}
 function stop(){timers.forEach(clearTimeout);timers=[];cancelAnimationFrame(frame)}
 function play(){stop();activate(0);if(!reduced)OPS_TIMELINE.slice(1).forEach((_,i)=>timers.push(setTimeout(()=>{if(root.classList.contains('ops-timeline-slide'))activate(i+1)},(i+1)*2400)))}
 root.querySelectorAll('.ops-stop').forEach(el=>el.onclick=()=>{stop();activate(Number(el.dataset.step))});root.querySelector('.ops-replay').textContent='Next step →';root.querySelector('.ops-replay').onclick=()=>{stop();activate((activeStep+1)%OPS_TIMELINE.length)};activate(0);
 window.opsCleanup=stop;const cleanup=()=>{stop();window.removeEventListener('hashchange',cleanup)};window.addEventListener('hashchange',cleanup);
}

function renderOpsScale(root){root.className='ops-scale-slide';root.innerHTML='<small>RESTAURANT PARTNERSHIPS</small><h2>Build affordable meals together.<br>Bring them to more markets.</h2><p>Restaurants create the meals. DoorDash brings discovery and demand.</p><div class="scale-numbers"><div><strong>7</strong><span>markets · end of H1 2026</span></div><div><strong>28</strong><span>markets · expansion footprint</span></div><div><strong>~165</strong><span>pre-sales reps · offsite snapshot</span></div></div><small>Activation SLA: POS merchants 12 days · tablet merchants 6 days. Elapsed time, not rep labor. 28 is the expansion footprint, not a new future target.</small>';}
const OPS_DETAILS={
 enroll:{step:1,title:'Human persuasion. Merchant-led setup.',before:'Reps coordinate each handoff',steps:['Today: reach merchants individually, explain the opportunity and discuss economics; meeting counts and duration still unverified','Co-create 3+ meals, coordinate photography, enter menu details and resolve activation handoffs','Self-service moves requirements, meal entry, photos and status into the portal. People keep persuasion, advice and exceptions'],baseline:'12 / 6 days',unit:'POS / tablet activation SLA · elapsed time',after:'Self-enrollment spans discovery and setup. Keep the relationship; reduce repeated coordination.',visual:'Self-enrollment prototype',form:'desktop',caption:'Program → requirements → create meals → submit · WIP',saving:'Projected time saving · estimate needed'},
 quality:{step:2,title:'Let customers help us see quality',before:'People gather and interpret the evidence',steps:['Manual testing means ordering a meal, assessing it, recording evidence and following up; not every SKU is taste-tested','22k SKUs created in the offsite snapshot. Weekly creation rate, tester headcount and hours per test still need a source','Customer photos + AI-assisted triage broaden the evidence. Humans investigate uncertain or poor-quality meals'],baseline:'1,384',unit:'photo-bearing submissions · Sept 9–21',after:'Customer photos + AI-assisted signals + human judgment',visual:'Consumer review flow',form:'phone',caption:'Review → add a photo → submit',saving:'Time saved · not measured'},
 report:{step:2,title:'Make useful feedback repeatable',before:'Reps assemble and explain the results',steps:['Gather performance and SKU reviews','Turn findings into recommendations','Email, discuss and follow up with merchants'],baseline:'Not measured',unit:'Rep time per reporting cycle',after:'A useful email first. A real person when needed.',visual:'Automated performance email',form:'email',caption:'Results → recommendations → ratings & reviews',saving:'Projected time saving · estimate needed'}
};
function renderOpsDetail(root,kind){const d=OPS_DETAILS[kind];root.className='ops-detail';root.innerHTML='<nav class="ops-phases" aria-label="Process stage">'+['Find','Build','Maintain'].map((x,i)=>'<span class="'+(i===d.step?'selected':'')+'">'+x+'</span>').join('')+'</nav><div class="ops-detail-copy"><h2>'+d.title+'</h2><p>'+d.before+'</p><ol>'+d.steps.map(x=>'<li>'+x+'</li>').join('')+'</ol><div class="ops-baseline"><strong>'+d.baseline+'</strong><small>'+d.unit+'</small></div><div class="ops-proposal"><b>'+d.after+'</b><small>'+d.saving+'</small></div></div><div class="ops-detail-visual"><div class="ops-demo '+d.form+'"><span>'+d.visual+'</span><small>'+d.caption+'</small><em>Prototype placeholder</em></div>'+(kind==='report'?'<button class="ops-open-report">View ratings & reviews →</button>':'')+'</div>';if(kind==='enroll'){const map=document.createElement('p');map.className='ops-scope-map';map.textContent='From the timeline: create & approve → setup & activation. Sales persuasion and exceptions remain human.';root.querySelector('.ops-detail-copy').append(map)}if(kind==='quality'){const phone=root.querySelector('.ops-demo.phone');phone.classList.add('review-prototype');phone.innerHTML='<iframe title="Meal Box consumer review prototype" src="../consumer-prototype/index.html?state=tracking&embed=1"></iframe>';new ResizeObserver(()=>phone.style.setProperty('--review-scale',phone.clientWidth/393)).observe(phone);const gallery=document.createElement('div');gallery.className='quality-evidence-gallery';gallery.innerHTML='<figure><div>Customer photo</div><figcaption>Meets the bar · photo to verify</figcaption></figure><figure><div>Customer photo</div><figcaption>Needs follow-up · photo to verify</figcaption></figure>';root.querySelector('.ops-detail-visual').append(gallery)}if(kind==='report'){const demo=root.querySelector('.ops-demo');demo.className='report-prototype';demo.innerHTML='<iframe title="Merchant email to ratings and reviews" src="../merchant-report/index.html?revision=real-email"></iframe>';root.querySelector('.ops-open-report')?.remove();new ResizeObserver(()=>demo.style.setProperty('--report-scale',demo.clientWidth/1100)).observe(demo)}if(!matchMedia('(prefers-reduced-motion: reduce)').matches){root.querySelector('.ops-detail-copy').animate([{opacity:0,transform:'translateY(16px)'},{opacity:1,transform:'translateY(0)'}],{duration:650});root.querySelector('.ops-detail-visual').animate([{opacity:0,transform:'translateY(24px) scale(.97)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:900,delay:150,fill:'backwards'})}}
