/* Presentation variants. Illustrative workload is not a measured program result. */
const baseMerchantStory=renderMerchantStory;
let opsVersion='B';
const OPS_PHASES=['Find, pitch & enroll','Check quality','Report & support'];
function opsRail(active){return '<div class="persistent-rail">'+OPS_PHASES.map((x,i)=>'<div class="rail-step '+(i===active?'active':'')+'"><span>0'+(i+1)+'</span><b>'+x+'</b></div>').join('')+'</div>'}
function opsWorkload(kind){const names={enroll:['Merchant setup','Rep touchpoints','Minutes per setup'],quality:['Meals to assess','Minutes per assessment','Hours of review'],report:['Merchant reports','Minutes per report','Hours per cycle']};if(kind)return '<div class="workload-numbers">'+names[kind].map(x=>'<div><strong>—</strong><span>'+x+'</span></div>').join('')+'</div><small class="workload-disclaimer">Baseline to verify · no measured time-saving claim</small>';return '<div class="workload-numbers"><div><strong data-count="30">0</strong><span>merchant conversations / rep / day</span></div><div><strong data-count="20">0</strong><span>minutes per conversation</span></div><div><strong data-count="10">0</strong><span>hours of conversations alone</span></div></div><small class="workload-disclaimer">Illustrative scenario—not actual staffing data. 30 × 20 min ÷ 60 = 10 hours, before setup or follow-up.</small>'}
renderMerchantStory=function(s){const previous={};document.querySelectorAll('[data-phase]').forEach(el=>previous[el.dataset.phase]=el.getBoundingClientRect());baseMerchantStory(s);if(!['process','enroll','quality','report'].includes(s.merchant))return;const root=document.querySelector('#slide');const nav=document.createElement('div');nav.className='ops-version-switch';nav.innerHTML=['A','B'].map(v=>'<button data-v="'+v+'" aria-pressed="'+(opsVersion===v)+'">'+v+' · '+(v==='A'?'Total workload':'Follow the timeline')+'</button>').join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{opsVersion=b.dataset.v;sessionStorage.setItem('ops-version',opsVersion);render()});
if(opsVersion==='B'){renderUnifiedTimeline(root,s.merchant,previous,nav);return;}
if(s.merchant==='process'){root.classList.add('ops-comparison');root.querySelector('.ops-clock').hidden=true;root.querySelector('.ops-evidence').hidden=true;const next=root.querySelector('.ops-replay');next.textContent='Show the scaling challenge →';next.onclick=()=>{root.classList.add('workload-focus');root.querySelector('.ops-context').animate([{opacity:1,transform:'translateX(0)'},{opacity:0,transform:'translateX(-70px)'}],{duration:600,fill:'forwards'});const timeline=root.querySelector('.ops-timeline');const before=timeline.getBoundingClientRect();timeline.classList.add('shifted');const after=timeline.getBoundingClientRect();timeline.animate([{transform:'translateX('+(before.left-after.left)+'px)'},{transform:'translateX(0)'}],{duration:900,easing:'cubic-bezier(.22,1,.36,1)'});next.hidden=true;const panel=document.createElement('section');panel.className='workload-panel';panel.innerHTML=opsVersion==='A'?'<h2>One rep.<br>More work than fits in a day.</h2>'+opsWorkload(): '<h2>Scale each step.<br>Keep people where they matter.</h2>'+opsRail(1)+'<p>Next: enrollment → quality → reporting.<br>The timeline stays with us.</p>';root.append(panel);panel.animate([{opacity:0,transform:'translateY(20px)'},{opacity:1,transform:'translateY(0)'}],{duration:700,delay:400,fill:'backwards'});panel.querySelectorAll('[data-count]').forEach(el=>{const target=+el.dataset.count,start=performance.now();function tick(t){if(!el.isConnected)return;const k=Math.min(1,(t-start)/1000);el.textContent=Math.round(target*k);if(k<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)})};
}else if(opsVersion==='B'){root.classList.add('timeline-continuation');root.querySelector('.ops-phases').remove();const rail=document.createElement('aside');rail.className='continued-timeline';const active={enroll:1,quality:2,report:3}[s.merchant];rail.innerHTML=opsRail(active)+opsWorkload(s.merchant);root.prepend(rail);root.querySelector('.ops-baseline').hidden=true;}
};

function renderUnifiedTimeline(root,kind,previous,nav){
 const active={enroll:0,quality:1,report:2}[kind]??-1,d=OPS_DETAILS[kind];
 const visual=root.querySelector('.ops-detail-visual');
 root.className='unified-ops'+(kind==='process'?' unified-overview':'');
 root.innerHTML='<section class="unified-timeline">'+(active<0?'<h2>Scaling the program means<br>scaling the work</h2>':'')+OPS_PHASES.map((name,i)=>'<article data-phase="'+i+'" class="unified-step '+(i===active?'expanded':'')+'"><span class="unified-dot">'+(i+1)+'</span><div><h3>'+name+'</h3>'+(i===active?'<div class="unified-expanded"><ol>'+(kind==='enroll'?['Find the right merchants and pitch the opportunity','Co-create meals and resolve setup details','Let merchants enter meals, upload photos and track activation']:kind==='quality'?['Order meals and check portions, balance and accuracy','Collect customer photos across more of the menu','Review quality signals and follow up with merchants']:['Gather performance and customer feedback','Show merchants what is working—and what needs attention','Connect the report to detailed reviews and next steps']).map(x=>'<li>'+x+'</li>').join('')+'</ol><p>'+d.after+'</p><div class="unified-metric">'+(kind==='quality'?'<strong>370 → <span data-total="900">0</span></strong><small>Photo reviews / week · before → after incentives<br>SKU coverage: 280 → 677 per week · Jade, September 2<br>In-app incentive: $5/meal vs. $15/meal taste testing (not total labor cost)</small>':kind==='enroll'?'<strong>Fewer manual handoffs</strong><small>Human outreach + merchant-led setup</small>':'<strong>Feedback → action</strong><small>A performance email connects to detailed merchant reviews</small>')+'</div><small class="unified-caveat">'+d.saving+'</small></div>':active<0?'<p>'+['Reach out, pitch the opportunity, co-create meals and coordinate activation','Gather evidence, assess meals and follow up on problems','Assemble results, recommend changes and maintain the relationship'][i]+'</p>':'')+'</div></article>').join('')+'</section>';
 // Comparison controls stay out of the presentation.
 if(visual){visual.className='unified-visual';root.append(visual);if(kind==='quality'){visual.querySelector('.quality-evidence-gallery')?.remove();const wall=document.createElement('div');wall.className='quality-photo-wall';const layout=new URLSearchParams(location.search).get('qualityLayout')||'wall';root.dataset.qualityLayout=['grid','wall','diagonal'].includes(layout)?layout:'wall';const photos=window.REVIEW_PHOTOS||[{file:'review-1.jpg',label:'Meal photo',sourceKind:'September offsite'}];const sequence=root.dataset.qualityLayout==='grid'?photos.slice(0,6):photos;wall.innerHTML=sequence.map(photo=>'<figure tabindex="0" title="'+photo.sourceKind+'"><img src="/assets/deck-final/affordable-meals/customer-reviews/'+photo.file+'" alt="'+photo.sourceKind+' meal photograph" loading="lazy"></figure>').join('');visual.append(wall)}}else{const intro=document.createElement('div');intro.className='unified-intro';intro.innerHTML=''}
 if(!matchMedia('(prefers-reduced-motion: reduce)').matches){root.querySelectorAll('[data-phase]').forEach(el=>{const old=previous[el.dataset.phase],now=el.getBoundingClientRect();if(old)el.animate([{transform:'translate('+(old.left-now.left)+'px,'+(old.top-now.top)+'px)'},{transform:'translate(0,0)'}],{duration:800,easing:'cubic-bezier(.22,1,.36,1)'});});root.querySelector('.unified-expanded')?.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:650,delay:250,fill:'backwards'});}
 root.querySelectorAll('[data-total]').forEach(el=>{const target=+el.dataset.total,start=performance.now(),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;function count(t){if(!el.isConnected)return;const k=reduce?1:Math.min(1,(t-start)/1200);el.textContent=Math.round(target*(1-Math.pow(1-k,3))).toLocaleString();if(k<1)requestAnimationFrame(count)}requestAnimationFrame(count)});
}
