// Presentation motion only. No games or simulated product actions.
const consumerTitles=['Introduce the program during everyday browsing.','Offer another route when customers keep looking.','Make affordable meals part of the search.','Introduce the program through a store they trust.','Carry the promise through checkout.'];
const motionLabels=['Browse','Keep looking','Search','Trusted store','Checkout'];
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
let previousMotion=-1;
function presentationMotion(s){const step=consumerTitles.indexOf(s.title),stage=document.querySelector('.stage');if(step>=0){document.querySelector('.copy').innerHTML=`<div class="eyebrow">THE CUSTOMER EXPERIENCE</div><h2 class="headline">Meet customers<br>where they are.</h2><div class="body">Make an everyday offer clear in familiar moments.</div><div class="chapter-steps">${motionLabels.map((label,i)=>`<button data-chapter="${i}" class="${i===step?'selected':''}"><span>0${i+1}</span>${label}</button>`).join('')}</div>`;
const frames=[['Good evening','Meal Box','Everyday meals, in one place'],['Still looking?','More meal options','A new route from browsing'],['Search meals','Meals for your search','Meet existing intent'],['Your neighborhood restaurant','Meal Box collection','Explain the offer in context'],['Your meal is on its way','Order confirmed','Carry the promise through']];const f=frames[step];stage.innerHTML=`<div class="motion-phone"><div class="phone-island"></div><div class="screen"><div class="screen-top">${f[0]}</div><div class="screen-search">${step===2?'Rice bowls':'Find your next meal'}</div><div class="food-block"><div class="meal-disc"></div></div><h3>${f[1]}</h3><div class="skeleton-line"></div><div class="skeleton-line short"></div><div class="screen-row"><div></div><div></div></div><div class="screen-bottom">${step===4?'✓ Thank you':'Explore meals →'}</div></div></div><div class="motion-detail"><small>${step===3?'DETAIL / EDUCATION':`0${step+1} / ${motionLabels[step].toUpperCase()}`}</small><h3>${f[2]}</h3><p>${esc(s.body)}</p><div class="detail-placeholder">${esc(s.visuals[s.visuals.length-1].label)}</div></div><div class="motion-caption">Illustrative layout · replace with your actual product screens</div>`;
document.querySelector('#slide').classList.add('consumer-minimal');const label=document.createElement('div');label.className='consumer-label';label.textContent=motionLabels[step];stage.appendChild(label);const index=document.createElement('div');index.className='consumer-index';index.setAttribute('aria-label','Consumer journey steps');index.innerHTML=motionLabels.map((name,i)=>`<button data-chapter="${i}" class="${i===step?'active':''}" aria-label="${name}" title="${name}">${String(i+1).padStart(2,'0')}</button>`).join('');stage.appendChild(index);
document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{current=SLIDES.findIndex(x=>x.title===consumerTitles[Number(b.dataset.chapter)]);render()});if(!reduced()){const dir=step>=previousMotion?1:-1;stage.querySelector('.screen').animate([{transform:`translateY(${dir*220}px)`,opacity:0},{transform:'translateY(0)',opacity:1}],{duration:1100,easing:'cubic-bezier(.2,.8,.2,1)'});stage.querySelector('.motion-detail').animate([{transform:step===3?'translateX(-45px) scale(.85)':'translateY(70px)',opacity:0},{transform:'none',opacity:1}],{duration:1000,easing:'cubic-bezier(.2,.8,.2,1)'});}const replay=document.createElement('button');replay.className='replay-motion';replay.textContent='↻ Replay transition';replay.onclick=()=>presentationMotion(s);stage.appendChild(replay);previousMotion=step;return}
previousMotion=-1;if(!reduced()){stage.querySelectorAll('.object').forEach((el,i)=>el.animate([{opacity:0,transform:`translateY(${18+i*7}px) scale(.96)`},{opacity:1,transform:'none'}],{duration:550,delay:i*65,fill:'backwards',easing:'cubic-bezier(.2,.8,.2,1)'}))}}
