/* Presentation adapter. Source UI remains the supplied affordability hub. */
(()=>{const mode=new URLSearchParams(location.search).get('view')||'lunch';let ready=false;const style=document.createElement('style');style.textContent=`html,body{margin:0!important;width:426px!important;height:898px!important;overflow:hidden!important}body>div:not([hidden]){width:426px!important;height:898px!important}div[style*="width: 426px"],div[style*="width:426px"]{transform:none!important;position:absolute!important;left:0!important;top:0!important;box-shadow:none!important}div[style*="width:272px"],div[style*="width: 272px"]{display:none!important}body{background:transparent!important}`;document.head.append(style);
const fonts=document.createElement('link');fonts.rel='stylesheet';fonts.href='/review/hub-next/local-fonts.css';document.head.append(fonts);
const localBanners={'/dd kitchen banner.png':'/review/hub-next/dd-kitchen-banner.png','/12-or-less-banner.png':'/review/hub-next/hero-12-menu-6c9887.png'};
const unavailablePhotos=new Set(['928022cc-493d-483b-b528-3bf2b0de261a','95c9a474-863c-4147-990c-558b1fda2bff']);
function localPhoto(url){let source;try{source=new URL(url,location.href)}catch{return null}const match=source.pathname.match(/\/media\/photosV2\/([a-f0-9-]{36})-retina-large\.(jpe?g|png)$/);if(!match)return null;const [,id,extension]=match;if(source.hostname==='img.cdn4dd.com'){return unavailablePhotos.has(id)?null:`/review/hub-next/product-photos/${id}.jpg`}if(source.hostname==='doordash-static.s3.amazonaws.com')return `/review/hub-next/product-photos/${id}.${extension}`;return null}
function restoreAssets(){document.querySelectorAll('img').forEach(img=>{const path=decodeURIComponent(new URL(img.src,location.href).pathname);const local=localBanners[path]||localPhoto(img.src);if(local&&img.getAttribute('src')!==local)img.src=local;});document.querySelectorAll('[style*="background-image"]').forEach(el=>{let value=el.style.backgroundImage;for(const [missing,local] of Object.entries(localBanners))value=value.replace(missing,local).replace(encodeURI(missing),local);value=value.replace(/https:\/\/[^"'() ]+\/media\/photosV2\/([a-f0-9-]{36})-retina-large\.(?:jpe?g|png)/g,url=>localPhoto(url)||url);if(value!==el.style.backgroundImage)el.style.backgroundImage=value;});}
new MutationObserver(restoreAssets).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['src','style']});restoreAssets();
const timer=setInterval(()=>{const group=document.querySelector('[aria-label="Day part"]');if(!group)return;const button=[...group.querySelectorAll('button')].find(b=>b.textContent.trim()===(mode==='breakfast'?'Breakfast':'Lunch'));if(!button)return;if(!ready){button.click();ready=true;return}const controls=group.parentElement;controls.style.display='none';if(mode==='kitchen'){const title=[...document.querySelectorAll('div')].find(e=>e.children.length===0&&e.textContent==='DoorDash Kitchen');let sc=title?.parentElement;while(sc&&getComputedStyle(sc).overflowY!=='auto')sc=sc.parentElement;if(sc&&title)sc.scrollTop+=title.getBoundingClientRect().top-sc.getBoundingClientRect().top-115;}clearInterval(timer)},150);setTimeout(()=>clearInterval(timer),12000)})();
